# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               JYCSEC
tagline:             'Thrill Seeker with Hacking Issues'
description:         'Just here to post my stories on security, running, traveling, learning music, and psychology!'
url:                 https://jycsec.com
baseurl:             ''
gems:			[jekyll-paginate]
paginate:            5

collections:
  fitness:
    output: true
    permalink: /fitness/:name
  psychology:
    output: true
    permalink: /psychology/:name
  music:
    output: true
    permalink: /music/:name
  gaming:
    output: true
    permalink: /gaming/:name
  cars:
    output: true
    permalink: /cars/:name
  travel:
    output: true
    permalink: /travel/:name


# About/contact
author:
  name:              Ju Youn Chae
  url:               https://jycsec.com/
  email:             hello@jycsec.com

# Custom vars
version:             1.0.0

# Google Analytics
google_analytics: UA-134454203-1
